# Mi primer Terraform CI pipeline
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Verificar Versión
        run: terraform version

      - name: Formatear Código
        run: terraform fmt -check

      - name: Validar Configuración
        run: terraform validate

      - name: Generar Plan
        run: terraform plan

      - name: Aplicar Infraestructura
        run: terraform apply -auto-approve
